save_config_on_exit = false
color_theme = "/usr/share/btop/themes/tokyo-night.theme"
graph_symbol = "block"
update_ms = 300
shown_boxes = "proc cpu net disk"
proc_sorting = "cpu direct"
proc_tree = true
proc_left = true
proc_aggregate = true
proc_mem_bytes = true
proc_cpu_graphs = true
vim_keys = true
base_10_sizes = true
cpu_invert_lower = true
show_cpu_watts = true
swap_disk = true
clock_format = "%X"
