version: v0.1.30
log:
    path: /tmp/vi-mongo.log
    level: info
    prettyPrint: true
editor:
    command: /usr/bin/nvim
    env: EDITOR
showConnectionPage: true
showWelcomePage: false
currentConnection: kiosk-demo
connections:
    - url: mongodb://localhost:27017
      host: localhost
      port: 27017
      database: ""
      username: ""
      password: ""
      name: kiosk-demo
      timeout: 5
      options: {}
    - url: mongodb://admin:admin@localhost:27017/academic_society?authSource=admin
      host: localhost
      port: 27017
      database: academic_society
      username: ""
      password: ""
      name: academic_society-dev
      timeout: 5
      options: {}
    - url: mongodb://admin:admin@localhost:27018/academic_society?authSource=admin
      host: localhost
      port: 27018
      database: academic_society
      username: ""
      password: ""
      name: academic_society-prod
      timeout: 5
      options: {}
styles:
    betterSymbols: true
    currentStyle: default.yaml
