version: 1.0.0
log:
    path: /tmp/vi-mongo.log
    level: info
    prettyPrint: true
editor:
    command: /usr/bin/nvim
    env: EDITOR
showConnectionPage: true
showWelcomePage: false
currentConnection: mongodb://localhost:27017/academic_society
connections:
    - url: mongodb://localhost:27017
      host: localhost
      port: 27017
      database: ""
      username: ""
      password: ""
      name: kiosk-demo
      timeout: 5
      options: {}
    - url: mongodb://localhost:27017/academic_society
      host: localhost
      port: 27017
      database: academic_society
      username: ""
      password: ""
      name: mongodb://localhost:27017/academic_society
      timeout: 5
      options: {}
styles:
    betterSymbols: true
    currentStyle: default.yaml
