session_name: system-configuration
start_directory: ${HOME}
suppress_history: false
windows:
    - window_name: packages
      layout: main-horizontal
      panes:
        - shell_command: sudo pacman -Syyu
          focus: 'true'
        - shell_command: yay -Syyu

    - window_name: SSH
      start_directory: ${HOME}/.local/state/bash.sub/
      layout: even-horizontal
      panes:
        - shell_command: vi ssh.sh
        - shell_command:
            - cd ${HOME}/.ssh/
            - vi $(ls | fzf --preview 'bat {}')

    - window_name: API keys
      start_directory: ${HOME}/.local/state/bash.sub/
      panes:
        - shell_command: cat api-key.sh | less

    - window_name: tmux-session
      start_directory: ${HOME}/.tmuxp/
      panes:
        - shell_command: vi $(ls *.yaml | fzf --preview='bat {}')

    - window_name: tmux-resurrect
      start_directory: ${HOME}/.local/state/tmux-resurrects/
      panes:
        - shell_command: watch -n 1 'ls -l'
        - shell_command:
            - cmd: ln -sf "$(ls tmux_resurrect_*.txt | fzf --reverse --preview='bat {}')" last
              enter: true
