session_name: system-configuration
start_directory: ${HOME}
suppress_history: false
windows:
  - window_name: packages
    layout: even-horizontal
    panes:
      - shell_command: sudo pacman -Syyu
        focus: true
      - shell_command: yay -Syyu

  - window_name: bash & subs
    layout: main-vertical
    panes:
      - shell_command: vi ${HOME}/.bashrc
      - shell_command: vi ${HOME}/.config/bash.sub/
        focus: true

  - window_name: T-session
    start_directory: ${TMUXP_CONFIGDIR}
    panes:
      - shell_command: sel=$(ls --reverse *.yaml | fzf --header="Edit the selected session spec" --preview="bat --color=always {}"); [ -n "$sel" ] && vi $sel

  - window_name: T-resurrect
    start_directory: ${TMUX_RESURRECT_DIR}
    panes:
      - shell_command: watch -n 1 'ls -l'
      - shell_command:
          - cmd: ln -sf "$(ls tmux_resurrect_*.txt | fzf --reverse --header="Replace the current resurrect point, with '--force'" --preview='bat {}')" last
            enter: true

  - window_name: SSH
    start_directory: ${HOME}/.local/state/bash.sub/
    layout: even-horizontal
    panes:
      - shell_command: vi ssh.sh
        focus: true
      - shell_command:
          - cd ${HOME}/.ssh/
          - sel=$(ls | fzf --header="Open with neovim with read only option" --preview "bat --color=always {}"); [ -n "$sel" ] && vi -R $sel

  - window_name: API keys
    start_directory: ${HOME}/.local/state/bash.sub/
    panes:
      - shell_command: cat api-key.sh | less
